---
- name: This sets up an httpd webserver
  hosts: localhost
  tasks:  
  - name: Install apache packages AWS
    yum:
      name: httpd
      state: present
    when: ansible_facts['os_family'] == "Amazon"
  - name: Install apache packages Azure
    apt: name=apache2 update_cache=yes state=present
    when: ansible_facts['os_family'] == "Ubuntu"
  - name: Create a default page
    shell: echo "<h1>Hello world from Packer & Ansible</h1>" > /var/www/html/index.html
    changed_when: false